### ISSUE TITLE
Support custom certificates (BYOC)

### ISSUE THREAD

**Issue by itakouna** [gridscale/gridscale_api_client_python#13]
API client should support custom certificates, which will be are used by LBaaS.

**Comment by Aldemuro** [comment]
The change for this request is currently on test. If everything looks good, this will be available in the next version

**Comment by itakouna** [comment]
Tested and worked fine 👍

**Comment by itakouna** [comment]
@Aldemuro have you released the new version?

**Comment by Aldemuro** [comment]
@itakouna yes, was released couple minutes a go. thanks for testing 
https://pypi.org/project/gs-api-client

**Comment by itakouna** [comment]
Thanks @Aldemuro

**Comment by itakouna** [comment]
Released in version `1.1.5`
