### ISSUE TITLE
examples.py breaks when a template is removed

### ISSUE THREAD

**Issue by BoxG11** [gridscale/gridscale_api_client_python#19]
In the example file it currently tries to use Debian 9 as a template.

We could just change to the newest Debian version for the example. However, this will just break whenever we depreciate Debian 11.

Another option would be to implement a default option which would always use the newest Debian version.

**Comment by bkircher** [comment]
@jonathanlutterbeck is this already done?

**Comment by BoxG11** [comment]
Hello, yes. I changed the used version to Debian 11.

**Comment by bkircher** [comment]
Excellent
